---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
        - name: cache
          image: valkey/valkey:8
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
        - name: web
          image: __WEB_SERVICE_IMAGE__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: web-config
          env:
            - name: DJANGO_ENVIRONMENT
              value: "production"
            - name: DJANGO_DEBUG
              value: "True"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: SECRET_KEY
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_DB
