# Settings for use during local development

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "0.0.0.0:3901"
rpc_secret = "0000000000000000000000000000000000000000000000000000000000000000"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.s3"
index = "index.html"

[admin]
api_bind_addr = "0.0.0.0:3903"
admin_token = "garage-admin-token-local-dev-only"
metrics_token  = "garage-metrics-token-local-dev-only"

[k2v_api]
api_bind_addr = "[::]:3904"
