target-version = "py311"
line-length = 80
lint.select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
lint.ignore = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
