[tools]
python = "3.13.3"
uv = "latest"
watchexec = "2.3"

[env]
_.python.venv = ".venv"
_.file = ".env"


[tasks.dev]
description = "Watch for changes in .env and run the development server"
run = "watchexec -r -w .env mise runserver"

[tasks.runserver]
description = "Run development server"
run = "python manage.py runserver"

[tasks.format]
description = "Format code with Ruff"
run = "ruff format ."

[tasks.check]
description = "Check code with Ruff"
run = "ruff check ."

[tasks.test]
env = { DJANGO_ENVIRONMENT = "testing" }
description = "Run tests"
run = "python manage.py test"

[tasks.migrate]
description = "Run database migrations"
run = "python manage.py migrate"

[tasks.makemigrations]
description = "Create new database migrations"
run = "python manage.py makemigrations"
