[tools]
python = "3.13"
uv = "0.6.13"
watchexec = "2.3"

[env]
_.python.venv = ".venv"
_.file = ".env"


[tasks.dev]
description = "Watch .env for changes and run development server"
run = "watchexec -r -w .env mise _dev"
silent = true

[tasks._dev]
description = "Run development server"
run = "python manage.py runserver"
silent = true

[tasks.format]
description = "Format code with Ruff"
run = "ruff format ."

[tasks.check]
description = "Check code with Ruff"
run = "ruff check ."

[tasks.test]
description = "Run tests"
run = "python manage.py test"

[tasks.migrate]
description = "Run database migrations"
run = "python manage.py migrate"

[tasks.makemigrations]
description = "Create new database migrations"
run = "python manage.py makemigrations"
