[tools]
python = "3.13.3"
uv = "0.6.13"
watchexec = "2.3"

[env]
_.python.venv = ".venv"
_.file = ".env"


[tasks.uv-sync-dev]
description = "Make sure that the project dependencies are installed"
run = "uv sync --locked"

[tasks.setup-dev]
# depends with multiple values messes up dev server output for some reason
# depends = ["_dotenvexists", "uv-sync-dev"]
run = [
    "mise run _dotenvexists",
    "mise run uv-sync-dev",
]

[tasks.dev]
depends = ["setup-dev"]
description = "Watch .env for changes and run development server"
run = "watchexec -r -w .env mise runserver"

[tasks.runserver]
description = "Run development server"
run = "python manage.py runserver"

[tasks._dotenvexists]
description = "Check that .env file exists or copy from .env.example"
hide = true
run = "[ ! -f .env ] && cp .env.example .env || true"

[tasks.format]
description = "Format code with Ruff"
run = "ruff format ."

[tasks.check]
description = "Check code with Ruff"
run = "ruff check ."

[tasks.test]
description = "Run tests"
run = "python manage.py test"

[tasks.migrate]
description = "Run database migrations"
run = "python manage.py migrate"

[tasks.makemigrations]
description = "Create new database migrations"
run = "python manage.py makemigrations"
