name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --locked

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --locked

      - name: Run tests
        run: uv run manage.py test
        env:
          DEBUG: "True"
          SECRET_KEY: "github-actions-test-key"
          ALLOWED_HOSTS: "localhost,127.0.0.1"
          DATABASE_URL: "sqlite:///db.sqlite3"
